version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name bukket-test2 --s3-location s3://bukket-test2/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src